spring.application.name=department-store-api

spring.autoconfigure.exclude=\
org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,\
org.springframework.boot.orm.jpa.HibernateJpaAutoConfiguration,\
org.springframework.boot.flyway.autoconfigure.FlywayAutoConfiguration

spring.main.banner-mode=console

logging.level.root=info
logging.level.org.springframework=info